//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demand
    {
        public int id { get; set; }
        public int idClient { get; set; }
        public int idAgent { get; set; }
        public int idTypeDem { get; set; }
        public Nullable<int> Address { get; set; }
        public Nullable<int> MinPrice { get; set; }
        public Nullable<int> MaxPrice { get; set; }
    
        public virtual Agents Agents { get; set; }
        public virtual Client Client { get; set; }
        public virtual TypeDemands TypeDemands { get; set; }
        public virtual DemandsApart DemandsApart { get; set; }
        public virtual DemandsHouse DemandsHouse { get; set; }
        public virtual DemandsLands DemandsLands { get; set; }
    }
}
