//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Houses
    {
        public int ObjectID { get; set; }
        public string TotalFloors { get; set; }
        public string Rooms { get; set; }
        public Nullable<double> TotalArea { get; set; }
    
        public virtual Objects Objects { get; set; }
    }
}
